### ISSUE TITLE
ChartQA link is no longer accessible

### ISSUE THREAD

**Issue by liuyifan22** [TempleX98/MoVA#6]
![image](https://github.com/user-attachments/assets/ca069e7a-cc63-4df4-a832-16ae48f28d77)

Hello, thanks for your great work! 

There seems to be a minor problem that the google drive link you provided for ChartQA images (and maybe eval_chartqa.py and annotations as well) is no longer accessible. Would you please check it out and renew the link when you are available, thanks!

**Comment by TempleX98** [comment]
Maybe you can try to download the ChartQA dataset on [huggingface](https://huggingface.co/datasets/ahmed-masry/ChartQA) and extract the images.

**Comment by liuyifan22** [comment]
Thank you for your timely reply!
