### ISSUE TITLE
ChartQA: problems with eval

### ISSUE THREAD

**Issue by liuyifan22** [TempleX98/MoVA#7]
Hello! It seems that your m4c_evaluater.py is not correctly updated, for eval_chartqa.py needs a ChartVQA class but it is not there. Would you please fix it, thanks!
![image](https://github.com/user-attachments/assets/d5ffb192-fc7e-46f0-acb4-8cc9e7bc0f9c)
![image](https://github.com/user-attachments/assets/fa90fe5a-0bc8-40d3-a96b-5922e15dcc95)

**Comment by TempleX98** [comment]
Thanks for your feedback. I have updated the m4c_evaluater.py file, please try again.

**Comment by liuyifan22** [comment]
Thanks! It helped!
